/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as EraEraRouteImport } from './routes/era.$era'
import { Route as EraEraIndexRouteImport } from './routes/era.$era.index'
import { Route as EraEraConceptRouteImport } from './routes/era.$era.$concept'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const EraEraRoute = EraEraRouteImport.update({
  id: '/era/$era',
  path: '/era/$era',
  getParentRoute: () => rootRouteImport,
} as any)
const EraEraIndexRoute = EraEraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EraEraRoute,
} as any)
const EraEraConceptRoute = EraEraConceptRouteImport.update({
  id: '/$concept',
  path: '/$concept',
  getParentRoute: () => EraEraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/era/$era': typeof EraEraRouteWithChildren
  '/era/$era/$concept': typeof EraEraConceptRoute
  '/era/$era/': typeof EraEraIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/era/$era/$concept': typeof EraEraConceptRoute
  '/era/$era': typeof EraEraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/era/$era': typeof EraEraRouteWithChildren
  '/era/$era/$concept': typeof EraEraConceptRoute
  '/era/$era/': typeof EraEraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/embed' | '/era/$era' | '/era/$era/$concept' | '/era/$era/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/embed' | '/era/$era/$concept' | '/era/$era'
  id:
    | '__root__'
    | '/'
    | '/embed'
    | '/era/$era'
    | '/era/$era/$concept'
    | '/era/$era/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedRoute: typeof EmbedRoute
  EraEraRoute: typeof EraEraRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/era/$era': {
      id: '/era/$era'
      path: '/era/$era'
      fullPath: '/era/$era'
      preLoaderRoute: typeof EraEraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/era/$era/': {
      id: '/era/$era/'
      path: '/'
      fullPath: '/era/$era/'
      preLoaderRoute: typeof EraEraIndexRouteImport
      parentRoute: typeof EraEraRoute
    }
    '/era/$era/$concept': {
      id: '/era/$era/$concept'
      path: '/$concept'
      fullPath: '/era/$era/$concept'
      preLoaderRoute: typeof EraEraConceptRouteImport
      parentRoute: typeof EraEraRoute
    }
  }
}

interface EraEraRouteChildren {
  EraEraConceptRoute: typeof EraEraConceptRoute
  EraEraIndexRoute: typeof EraEraIndexRoute
}

const EraEraRouteChildren: EraEraRouteChildren = {
  EraEraConceptRoute: EraEraConceptRoute,
  EraEraIndexRoute: EraEraIndexRoute,
}

const EraEraRouteWithChildren =
  EraEraRoute._addFileChildren(EraEraRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedRoute: EmbedRoute,
  EraEraRoute: EraEraRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
